services:
  react-app:
    container_name: lpilogue-fe
    restart: on-failure
    image: hadoroke/lpilogue-fe:latest
    ports:
      - "3000:3000"
    networks:
      - lpilogue-network
    environment:
      BE_HOST: "lpilogue-be"
      BE_PORT: "8080"
      REC_HOST: "lpilogue-rec"
      REC_PORT: "5000"
    depends_on:
      - spring-boot-app
      - flask-app
      - cloudflare-app

  spring-boot-app:
    container_name: lpilogue-be
    restart: on-failure
    image: hadoroke/lpilogue-be:latest
    ports:
      - "8080:8080"
    networks:
      - lpilogue-network
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: jdbc:mysql://lpilogue-db:3306/lpilogue?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    depends_on:
      - mysql-app

  mysql-app:
    container_name: lpilogue-db
    image: mysql:8
    restart: always
    networks:
      - lpilogue-network
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - /mnt/tank/databases/mysql:/var/lib/mysql

  flask-app:
    container_name: lpilogue-rec
    restart: on-failure
    image: hadoroke/lpilogue-rec:latest
    networks:
      - lpilogue-network
    environment:
      TZ: Asia/Seoul
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      FILE_SERVER_URL: ${FILE_SERVER_URL}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - mysql-app

  cloudflare-app:
    container_name: cloudflare
    restart: unless-stopped
    image: cloudflare/cloudflared:latest
    networks:
      - lpilogue-network
    command: tunnel --no-autoupdate --protocol http2 run --token eyJhIjoiM2FhNmJmMjU1NzdmMDQ1OThhMjYyMGEwMzg4OWVkMzYiLCJ0IjoiM2EzNTk5MTItNmZhYi00OGM0LWIxMDktODRhOTFjMzVmN2MwIiwicyI6Ik9UVm1NV1l3TW1RdE9XWTNOQzAwWkdRd0xXRTJZalV0TldSaFpESTBZek01TjJGbSJ9

# 외부 네트워크 설정
networks:
  lpilogue-network:
    external: true